### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Lykeee** [rld-wma/rld-wma.github.io#2]
![Larks](https://github.com/user-attachments/assets/f600c6f9-600e-436c-baf3-d40c1cb018b4)
![Larks](https://github.com/user-attachments/assets/0681f31a-0b6c-4e6f-b511-1d0ec1b35664)
![Larks transparent BG](https://github.com/user-attachments/assets/2a436144-eb94-41b6-a8c0-0d4b7f2413f4)

**Comment by rld-wma** [comment]
inputted na po yung logo, then inaayos ko na rin po yung color base sa logo
